"""Strategy framework.

Base classes and 5 core strategies:
1. TREND_HOLD - 趋势持有
2. PULLBACK_SWING - 回调波段
3. RANGE_MEAN_REVERSION - 震荡均值回归
4. BEAR_REBOUND - 熊市反弹
5. CASH_DEFENSE - 现金防御
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import date
from typing import Optional

import pandas as pd

from a_share_quant.backtest import OrderEvent
from a_share_quant.regime import RegimeState


@dataclass
class StrategySignal:
    """Signal generated by a strategy."""
    symbol: str
    action: str  # BUY, SELL, HOLD
    strength: float  # 0-1
    reason: str
    entry_price: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    max_holding_days: int = 20
    metadata: dict = field(default_factory=dict)


@dataclass
class PositionInfo:
    """Current position information."""
    symbol: str
    quantity: int
    avg_cost: float
    sellable: int
    current_price: float
    unrealized_pnl: float
    holding_days: int


class BaseStrategy(ABC):
    """Base class for all strategies."""

    name: str = "BASE"
    description: str = ""

    def __init__(self, params: dict | None = None):
        self.params = params or {}

    @abstractmethod
    def generate_signal(
        self,
        symbol: str,
        df: pd.DataFrame,
        regime: RegimeState,
        position: Optional[PositionInfo],
        as_of_date: date,
    ) -> Optional[StrategySignal]:
        """Generate trading signal.

        Args:
            symbol: Stock symbol
            df: Historical daily bars
            regime: Current market regime
            position: Current position (None if no position)
            as_of_date: Signal date

        Returns:
            StrategySignal or None
        """
        pass

    def should_exit(
        self,
        position: PositionInfo,
        df: pd.DataFrame,
        regime: RegimeState,
        as_of_date: date,
    ) -> tuple[bool, str]:
        """Check if position should be exited.

        Returns:
            (should_exit, reason)
        """
        return False, ""


class TrendHoldStrategy(BaseStrategy):
    """趋势持有策略.

    Entry: Breakout above MA20 with volume confirmation
    Exit: Break below MA20 or trailing stop
    Best for: UP_LOW, UP_MEDIUM regimes
    """

    name = "TREND_HOLD"
    description = "趋势持有：突破均线入场，跟踪止损退出"

    def __init__(self, params: dict | None = None):
        default_params = {
            "ma_period": 20,
            "volume_ratio": 1.5,
            "trailing_stop_pct": 0.08,
            "max_holding_days": 60,
        }
        super().__init__({**default_params, **(params or {})})

    def generate_signal(
        self,
        symbol: str,
        df: pd.DataFrame,
        regime: RegimeState,
        position: Optional[PositionInfo],
        as_of_date: date,
    ) -> Optional[StrategySignal]:
        # Only trade in bullish regimes
        if not regime.is_bullish:
            return None

        df = df[df["trade_date"] <= as_of_date].tail(self.params["ma_period"] + 10)
        if len(df) < self.params["ma_period"]:
            return None

        close = df["close"].values
        volume = df["volume"].values

        ma = pd.Series(close).rolling(self.params["ma_period"]).mean().iloc[-1]
        avg_volume = pd.Series(volume).rolling(self.params["ma_period"]).mean().iloc[-1]

        current_price = close[-1]
        current_volume = volume[-1]

        # Entry: Price above MA and volume spike
        if position is None:
            if current_price > ma and current_volume > avg_volume * self.params["volume_ratio"]:
                stop_loss = current_price * (1 - self.params["trailing_stop_pct"])
                return StrategySignal(
                    symbol=symbol,
                    action="BUY",
                    strength=min(0.9, regime.confidence + 0.1),
                    reason=f"突破MA{self.params['ma_period']}，放量确认",
                    entry_price=current_price,
                    stop_loss=stop_loss,
                    take_profit=current_price * 1.20,
                    max_holding_days=self.params["max_holding_days"],
                )

        return None

    def should_exit(
        self,
        position: PositionInfo,
        df: pd.DataFrame,
        regime: RegimeState,
        as_of_date: date,
    ) -> tuple[bool, str]:
        df = df[df["trade_date"] <= as_of_date].tail(self.params["ma_period"] + 5)
        if len(df) < self.params["ma_period"]:
            return False, ""

        close = df["close"].values
        ma = pd.Series(close).rolling(self.params["ma_period"]).mean().iloc[-1]
        current_price = close[-1]

        # Exit if price breaks below MA
        if current_price < ma:
            return True, f"跌破MA{self.params['ma_period']}"

        # Trailing stop
        highest_since_entry = df["high"].max()
        trailing_stop = highest_since_entry * (1 - self.params["trailing_stop_pct"])
        if current_price < trailing_stop:
            return True, "触发跟踪止损"

        # Max holding period
        if position.holding_days >= self.params["max_holding_days"]:
            return True, "达到最大持有期"

        # Regime change
        if regime.is_bearish:
            return True, "市场转为熊市"

        return False, ""


class PullbackSwingStrategy(BaseStrategy):
    """回调波段策略.

    Entry: Pullback to MA in uptrend
    Exit: Bounce target or stop loss
    Best for: UP_MEDIUM, UP_HIGH, FLAT_MEDIUM regimes
    """

    name = "PULLBACK_SWING"
    description = "回调波段：上升趋势中回调买入"

    def __init__(self, params: dict | None = None):
        default_params = {
            "ma_period": 20,
            "pullback_pct": 0.05,
            "target_pct": 0.10,
            "stop_loss_pct": 0.05,
            "max_holding_days": 15,
        }
        super().__init__({**default_params, **(params or {})})

    def generate_signal(
        self,
        symbol: str,
        df: pd.DataFrame,
        regime: RegimeState,
        position: Optional[PositionInfo],
        as_of_date: date,
    ) -> Optional[StrategySignal]:
        # Need uptrend or flat
        if regime.is_bearish:
            return None

        df = df[df["trade_date"] <= as_of_date].tail(60)
        if len(df) < 30:
            return None

        close = df["close"].values
        ma = pd.Series(close).rolling(self.params["ma_period"]).mean().iloc[-1]
        current_price = close[-1]

        # Recent high
        recent_high = max(close[-20:])

        # Entry: Pullback to MA after uptrend
        if position is None:
            pullback = (recent_high - current_price) / recent_high
            if pullback >= self.params["pullback_pct"] and current_price >= ma * 0.98:
                stop_loss = current_price * (1 - self.params["stop_loss_pct"])
                target = current_price * (1 + self.params["target_pct"])
                return StrategySignal(
                    symbol=symbol,
                    action="BUY",
                    strength=0.6 + pullback,
                    reason=f"回调{pullback:.1%}至均线支撑",
                    entry_price=current_price,
                    stop_loss=stop_loss,
                    take_profit=target,
                    max_holding_days=self.params["max_holding_days"],
                )

        return None

    def should_exit(
        self,
        position: PositionInfo,
        df: pd.DataFrame,
        regime: RegimeState,
        as_of_date: date,
    ) -> tuple[bool, str]:
        current_price = position.current_price

        # Stop loss
        if current_price < position.avg_cost * (1 - self.params["stop_loss_pct"]):
            return True, "触发止损"

        # Take profit
        if current_price > position.avg_cost * (1 + self.params["target_pct"]):
            return True, "达到止盈目标"

        # Max holding
        if position.holding_days >= self.params["max_holding_days"]:
            return True, "达到最大持有期"

        return False, ""


class RangeMeanReversionStrategy(BaseStrategy):
    """震荡均值回归策略.

    Entry: Price at lower Bollinger Band
    Exit: Price at middle or upper band
    Best for: FLAT_LOW, FLAT_MEDIUM regimes
    """

    name = "RANGE_MEAN_REVERSION"
    description = "震荡均值回归：布林带下轨买入，中轨/上轨卖出"

    def __init__(self, params: dict | None = None):
        default_params = {
            "bb_period": 20,
            "bb_std": 2.0,
            "stop_loss_pct": 0.05,
            "max_holding_days": 10,
        }
        super().__init__({**default_params, **(params or {})})

    def generate_signal(
        self,
        symbol: str,
        df: pd.DataFrame,
        regime: RegimeState,
        position: Optional[PositionInfo],
        as_of_date: date,
    ) -> Optional[StrategySignal]:
        # Best in flat/low volatility
        if regime.is_bearish and regime.oscillation.value == "HIGH":
            return None

        df = df[df["trade_date"] <= as_of_date].tail(self.params["bb_period"] + 10)
        if len(df) < self.params["bb_period"]:
            return None

        close = df["close"].values
        ma = pd.Series(close).rolling(self.params["bb_period"]).mean().iloc[-1]
        std = pd.Series(close).rolling(self.params["bb_period"]).std().iloc[-1]

        upper_band = ma + self.params["bb_std"] * std
        lower_band = ma - self.params["bb_std"] * std
        current_price = close[-1]

        # Entry: Price at or below lower band
        if position is None:
            if current_price <= lower_band * 1.01:
                stop_loss = current_price * (1 - self.params["stop_loss_pct"])
                return StrategySignal(
                    symbol=symbol,
                    action="BUY",
                    strength=0.7,
                    reason="触及布林带下轨",
                    entry_price=current_price,
                    stop_loss=stop_loss,
                    take_profit=ma,  # Target middle band
                    max_holding_days=self.params["max_holding_days"],
                )

        return None

    def should_exit(
        self,
        position: PositionInfo,
        df: pd.DataFrame,
        regime: RegimeState,
        as_of_date: date,
    ) -> tuple[bool, str]:
        df = df[df["trade_date"] <= as_of_date].tail(self.params["bb_period"] + 5)
        if len(df) < self.params["bb_period"]:
            return False, ""

        close = df["close"].values
        ma = pd.Series(close).rolling(self.params["bb_period"]).mean().iloc[-1]
        std = pd.Series(close).rolling(self.params["bb_period"]).std().iloc[-1]
        upper_band = ma + self.params["bb_std"] * std

        current_price = position.current_price

        # Exit at middle band (take profit)
        if current_price >= ma:
            return True, "回归均值"

        # Exit at upper band (extra profit)
        if current_price >= upper_band:
            return True, "触及上轨"

        # Stop loss
        if current_price < position.avg_cost * (1 - self.params["stop_loss_pct"]):
            return True, "触发止损"

        # Max holding
        if position.holding_days >= self.params["max_holding_days"]:
            return True, "达到最大持有期"

        return False, ""


class BearReboundStrategy(BaseStrategy):
    """熊市反弹策略.

    Entry: Oversold bounce signal in downtrend
    Exit: Quick profit taking
    Best for: DOWN_LOW, DOWN_MEDIUM regimes
    """

    name = "BEAR_REBOUND"
    description = "熊市反弹：超卖反弹，快进快出"

    def __init__(self, params: dict | None = None):
        default_params = {
            "rsi_period": 14,
            "rsi_oversold": 30,
            "target_pct": 0.05,
            "stop_loss_pct": 0.03,
            "max_holding_days": 5,
        }
        super().__init__({**default_params, **(params or {})})

    def _calculate_rsi(self, close: list[float], period: int) -> float:
        """Calculate RSI."""
        if len(close) < period + 1:
            return 50.0
        deltas = [close[i] - close[i-1] for i in range(1, len(close))]
        gains = [d if d > 0 else 0 for d in deltas[-period:]]
        losses = [-d if d < 0 else 0 for d in deltas[-period:]]
        avg_gain = sum(gains) / period
        avg_loss = sum(losses) / period
        if avg_loss == 0:
            return 100.0
        rs = avg_gain / avg_loss
        return 100 - (100 / (1 + rs))

    def generate_signal(
        self,
        symbol: str,
        df: pd.DataFrame,
        regime: RegimeState,
        position: Optional[PositionInfo],
        as_of_date: date,
    ) -> Optional[StrategySignal]:
        # Only in bearish regimes
        if not regime.is_bearish:
            return None

        df = df[df["trade_date"] <= as_of_date].tail(30)
        if len(df) < self.params["rsi_period"] + 5:
            return None

        close = df["close"].values.tolist()
        rsi = self._calculate_rsi(close, self.params["rsi_period"])
        current_price = close[-1]

        # Entry: RSI oversold
        if position is None:
            if rsi < self.params["rsi_oversold"]:
                stop_loss = current_price * (1 - self.params["stop_loss_pct"])
                target = current_price * (1 + self.params["target_pct"])
                return StrategySignal(
                    symbol=symbol,
                    action="BUY",
                    strength=0.5,
                    reason=f"RSI={rsi:.1f}超卖",
                    entry_price=current_price,
                    stop_loss=stop_loss,
                    take_profit=target,
                    max_holding_days=self.params["max_holding_days"],
                )

        return None

    def should_exit(
        self,
        position: PositionInfo,
        df: pd.DataFrame,
        regime: RegimeState,
        as_of_date: date,
    ) -> tuple[bool, str]:
        current_price = position.current_price

        # Quick stop loss
        if current_price < position.avg_cost * (1 - self.params["stop_loss_pct"]):
            return True, "触发止损"

        # Quick take profit
        if current_price > position.avg_cost * (1 + self.params["target_pct"]):
            return True, "达到反弹目标"

        # Very short holding period
        if position.holding_days >= self.params["max_holding_days"]:
            return True, "达到最大持有期"

        return False, ""


class CashDefenseStrategy(BaseStrategy):
    """现金防御策略.

    No new positions, exit existing positions.
    Best for: DOWN_HIGH regime (high volatility downtrend)
    """

    name = "CASH_DEFENSE"
    description = "现金防御：空仓观望，等待机会"

    def __init__(self, params: dict | None = None):
        default_params = {
            "exit_all": True,
        }
        super().__init__({**default_params, **(params or {})})

    def generate_signal(
        self,
        symbol: str,
        df: pd.DataFrame,
        regime: RegimeState,
        position: Optional[PositionInfo],
        as_of_date: date,
    ) -> Optional[StrategySignal]:
        # Never buy in defense mode
        return None

    def should_exit(
        self,
        position: PositionInfo,
        df: pd.DataFrame,
        regime: RegimeState,
        as_of_date: date,
    ) -> tuple[bool, str]:
        # Exit all positions in defense mode
        if self.params.get("exit_all", True):
            return True, "现金防御模式，清仓"
        return False, ""


# =============================================================================
# Strategy Registry
# =============================================================================

STRATEGY_REGISTRY: dict[str, type[BaseStrategy]] = {
    "TREND_HOLD": TrendHoldStrategy,
    "PULLBACK_SWING": PullbackSwingStrategy,
    "RANGE_MEAN_REVERSION": RangeMeanReversionStrategy,
    "BEAR_REBOUND": BearReboundStrategy,
    "CASH_DEFENSE": CashDefenseStrategy,
}


def get_strategy(name: str, params: dict | None = None) -> BaseStrategy:
    """Get strategy instance by name."""
    if name not in STRATEGY_REGISTRY:
        raise ValueError(f"Unknown strategy: {name}")
    return STRATEGY_REGISTRY[name](params)


def list_strategies() -> list[str]:
    """List all available strategies."""
    return list(STRATEGY_REGISTRY.keys())
